{% set name = "jsondiff" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5122bf4708a031b02db029366184a87c5d0ddd5a327a5884ee6cf0193e599d71

build:
  number: 0
  noarch: python
  entry_points:
    - jdiff=jsondiff.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - jsondiff
  commands:
    - jdiff --help

about:
  home: https://github.com/ZoomerAnalytics/jsondiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Diff JSON and JSON-like structures in Python

extra:
  recipe-maintainers:
    - mariusvniekerk
